Repository Quick-AI/quickvision, pull requests merged in 2020-11, with the labels that each got.

#32 fixes cuda tests
  quickvision/models/classification/cnn/engine.py
  quickvision/models/detection/detr/engine.py
  quickvision/models/detection/faster_rcnn/engine.py
  quickvision/models/detection/retinanet/engine.py
  tests/test_cnn.py
  tests/test_detr.py
Labels: Tests

#34 Fixes Model utils
  docs/templates/contributing.md
  docs/templates/index.md
  quickvision/__init__.py
  quickvision/losses/detr_loss.py
  quickvision/metrics/__init__.py
  quickvision/metrics/classification.py
  quickvision/models/__init__.py
  quickvision/models/classification/cnn/engine.py
  quickvision/models/detection/detr/engine.py
  quickvision/models/detection/faster_rcnn/engine.py
  quickvision/models/detection/retinanet/engine.py
  quickvision/models/model_utils.py
  quickvision/utils/__init__.py
  quickvision/utils/averaging_utils.py
  quickvision/utils/early_stopping_utlis.py
  quickvision/utils/nested_tensor_utils.py
  quickvision/utils/progress_utils.py
  quickvision/utils/torch_utils.py
  setup.py
  tests/test_detr.py
  tests/test_frcnn.py
  tests/test_retinanet.py
  tests/test_utils.py
Labels: Tests, enhancement

#40 Fixed typos
  CONTRIBUTING.md
  README.md
Labels: documentation

#39 Fixed CSVDataset and Added Tests
  quickvision/datasets/__init__.py
  quickvision/datasets/classification.py
  tests/assets/10001.png
  tests/assets/10002.png
  tests/assets/csv_dataset.csv
  tests/test_datasets.py
Labels: datasets

#44 Added notebooks and install instructions
  README.md
  docs/templates/index.md
  examples/notebooks/CNNs_with_Quickvision.ipynb
  examples/notebooks/README.md
Labels: documentation

#45 Changes pretrained to str for detr, fixes init bug for torchvision
  quickvision/models/components/torchvision_backbones.py
  quickvision/models/detection/detr/lightning_trainer.py
  quickvision/models/detection/detr/model_factory.py
  quickvision/pretrained/_pretrained_detection.py
  quickvision/pretrained/_pretrained_weights.py
  tests/test_detr.py
Labels: High Priority

#47 Makes Pretrained consistent
  quickvision/models/detection/detr/model_factory.py
  quickvision/models/detection/faster_rcnn/lightning_trainer.py
  quickvision/models/detection/retinanet/lightning_trainer.py
  tests/test_frcnn.py
  tests/test_retinanet.py
Labels: High Priority, bug

#49 Adds tests for schedular and swa
  quickvision/models/README.md
  quickvision/models/classification/README.md
  quickvision/models/classification/cnn/engine.py
  quickvision/models/detection/README.md
  quickvision/pretrained/README.md
  quickvision/tensorrt/README.md
  quickvision/tensorrt/__init__.py
  tests/test_cnn.py
  tests/test_smoke.py
Labels: Tests

#50 Adds type annotations
  quickvision/models/classification/cnn/engine.py
  quickvision/models/components/torchvision_backbones.py
  quickvision/models/detection/detr/engine.py
  quickvision/models/detection/detr/model_factory.py
  quickvision/models/detection/faster_rcnn/engine.py
  quickvision/models/detection/retinanet/engine.py
Labels: enhancement

#46 Complete sanity functions for faster_rcnn and RetinaNet
  quickvision/models/detection/faster_rcnn/__init__.py
  quickvision/models/detection/faster_rcnn/engine.py
  quickvision/models/detection/faster_rcnn/lightning_trainer.py
  quickvision/models/detection/faster_rcnn/model_factory.py
  quickvision/models/detection/retinanet/engine.py
  tests/test_frcnn.py
  tests/test_retinanet.py
Labels: High Priority, Model to Implement

#51 Adds Detr sanity fns
  quickvision/models/detection/detr/engine.py
  quickvision/models/detection/faster_rcnn/engine.py
  tests/test_detr.py
Labels: High Priority, Tests

#52 Adds Examples and Notebooks for Release !
  README.md
  examples/README.md
  examples/classification/config.py
  examples/classification/lightning_train.py
  examples/classification/qat_head_train.py
  examples/classification/qat_train.py
  examples/classification/quantization_aware_training.py
  examples/classification/training_sota_cnns.py
  examples/classification/transfer_learning_with_pytorch_lightning.py
  examples/detection/config.py
  examples/detection/quickvision_object_detection_tutorial.py
  examples/detection/training_detection_models_with_pytorch_lightning.py
  examples/notebooks/Quantization_Aware_Training.ipynb
  examples/notebooks/Quickstart.ipynb
  examples/notebooks/Quickvision_Object_Detection_Tutorial.ipynb
  examples/notebooks/README.md
  examples/notebooks/Training_Detection_models_with_PyTorch_Lightning.ipynb
  examples/notebooks/Training_SOTA_CNNs.ipynb
  examples/notebooks/Transfer_Learning_with_PyTorch_Lightning.ipynb
  quickvision/README.md
  quickvision/models/classification/cnn/engine.py
  setup.py
Labels: documentation, help wanted

#55 Patch files after release 1
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  setup.py
Labels: release

#57 Added Sphinx Documentation
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/mkdocs.yml
  docs/modules.rst
  docs/quickvision.datasets.rst
  docs/quickvision.layers.rst
  docs/quickvision.losses.rst
  docs/quickvision.metrics.rst
  docs/quickvision.models.classification.cnn.rst
  docs/quickvision.models.classification.rst
  docs/quickvision.models.components.rst
  docs/quickvision.models.detection.detr.rst
  docs/quickvision.models.detection.faster_rcnn.rst
  docs/quickvision.models.detection.retinanet.rst
  docs/quickvision.models.detection.rst
  docs/quickvision.models.rst
  docs/quickvision.models.segmentation.deeplab.rst
  docs/quickvision.models.segmentation.fcn.rst
  docs/quickvision.models.segmentation.rst
  docs/quickvision.optimizers.rst
  docs/quickvision.pretrained.rst
  docs/quickvision.rst
  docs/quickvision.utils.rst
  docs/requirements.txt
  docs/setup.rst
  docs/templates/contributing.md
  docs/templates/index.md
Labels: documentation
