Repository Quick-AI/quickvision, pull requests merged in 2020-12, with the labels that each got.

#58 Adds CI for docs, Refactors the docs
  .github/workflows/mk-docs-build.yml
  .github/workflows/mk-docs-deploy.yml
  .github/workflows/sphinx-docs-build.yml
  .github/workflows/sphinx-docs-deploy.yml
  docs/_static/styles.css
  docs/conf.py
  docs/requirements.txt
  docs/source/modules.rst
  docs/source/quickvision.datasets.rst
  docs/source/quickvision.layers.rst
  docs/source/quickvision.losses.rst
  docs/source/quickvision.metrics.rst
  docs/source/quickvision.models.classification.cnn.rst
  docs/source/quickvision.models.classification.rst
  docs/source/quickvision.models.components.rst
  docs/source/quickvision.models.detection.detr.rst
  docs/source/quickvision.models.detection.faster_rcnn.rst
  docs/source/quickvision.models.detection.retinanet.rst
  docs/source/quickvision.models.detection.rst
  docs/source/quickvision.models.rst
  docs/source/quickvision.models.segmentation.deeplab.rst
  docs/source/quickvision.models.segmentation.fcn.rst
  docs/source/quickvision.models.segmentation.rst
  docs/source/quickvision.optimizers.rst
  docs/source/quickvision.pretrained.rst
  docs/source/quickvision.rst
  docs/source/quickvision.utils.rst
  docs/source/setup.rst
Labels: Tests, documentation

#63 Drops timm, fixes docs
  .github/workflows/sphinx-docs-build.yml
  .github/workflows/sphinx-docs-deploy.yml
  .gitignore
  docs/index.rst
  docs/source/conf.py
  docs/source/setup.rst
  quickvision/models/classification/cnn/__init__.py
  quickvision/models/classification/cnn/model_factory.py
  requirements.txt
  tests/test_cnn.py
Labels: bug

#65 Cleans up code like bolts
  .github/workflows/sphinx-docs-build.yml
  .github/workflows/sphinx-docs-deploy.yml
  docs/source/modules.rst
  quickvision/models/components/torchvision_backbones.py
  quickvision/pretrained/_model_zoo.py
  quickvision/pretrained/_pretrained_cnns.py
Labels: Medium Priority

#68 Adding swav weights
  quickvision/pretrained/_model_zoo.py
  quickvision/pretrained/_pretrained_cnns.py
Labels: pretrained

#71 Initial Losses API Template
  quickvision/losses/__init__.py
  quickvision/losses/detr_loss.py
  quickvision/losses/dice_loss.py
  quickvision/losses/functional/__init__.py
  quickvision/losses/functional/dice_loss.py
Labels: losses

#76 Add WideResnet (#72)
  quickvision/models/components/torchvision_backbones.py
  quickvision/pretrained/_model_zoo.py
  quickvision/pretrained/_pretrained_cnns.py
  tests/test_torchvision_backbones.py
Labels: High Priority, Model to Implement

#77 Fixes CI and ecoding issue
  .github/workflows/install-pkg.yml
  requirements.txt
  setup.py
Labels: bug

#78 Update dummy detection dataset
  tests/dataset_utils.py
Labels: Tests

#79 Refactor test for detection
  tests/dataset_utils.py
  tests/test_detr.py
  tests/test_frcnn.py
  tests/test_retinanet.py
Labels: Tests

#81 Add W&B example Notebook
  examples/notebooks/Intro_to_Quickvision_with_W&B.ipynb
Labels: documentation

#74 DETR COCO example
  examples/detection/detr_coco/coco.py
  examples/detection/detr_coco/detr_train.py
  examples/detection/detr_coco/detr_transforms.py
Labels: documentation

#80 Adds basic layers
  quickvision/layers/__init__.py
  quickvision/layers/act_mish.py
  quickvision/layers/block_mlp.py
  quickvision/layers/functional/__init__.py
  quickvision/layers/functional/act_mish.py
Labels: layers

#84 Updates CI and docs for 0.1.1
  .github/workflows/ci-testing.yml
  SECURITY.md
  examples/README.md
  examples/classification/intro_to_quickvision_with_w&b.py
  requirements-test.txt
  setup.py
Labels: release

#87 Bump lightning to 1.1 for release
  requirements-test.txt
  requirements.txt
Labels: Tests

#88 Fixes requirements to be installable, fixes CUDA Tests
  .github/workflows/ci-testing.yml
  requirements-test.txt
  requirements.txt
  tests/test_cnn.py
  tests/test_detr.py
  tests/test_frcnn.py
  tests/test_retinanet.py
Labels: release

#91 Post release 0.1.1
  README.md
  quickvision/models/classification/cnn/model_factory.py
  setup.py
Labels: release

#92 Renames to Follow Conventions
  quickvision/models/classification/cnn/__init__.py
  quickvision/models/classification/cnn/lightning_trainer.py
  quickvision/models/classification/cnn/model_factory.py
  quickvision/models/detection/detr/__init__.py
  quickvision/models/detection/detr/lightning_trainer.py
  quickvision/models/detection/detr/model_factory.py
  quickvision/models/detection/faster_rcnn/__init__.py
  quickvision/models/detection/faster_rcnn/lightning_trainer.py
  quickvision/models/detection/faster_rcnn/model_factory.py
  quickvision/models/detection/retinanet/__init__.py
  quickvision/models/detection/retinanet/lightning_trainer.py
  quickvision/models/detection/retinanet/model_factory.py
  tests/test_cnn.py
  tests/test_datasets.py
  tests/test_detr.py
  tests/test_frcnn.py
  tests/test_retinanet.py
  tests/test_smoke.py
Labels: BC Breaking, High Priority

#95 Adds CodeQL Analysis
  .github/workflows/codeql-analysis.yml
Labels: Tests

#96 cache codeql
  .github/workflows/codeql-analysis.yml
Labels: Tests

#97 remove cache useless
  .github/workflows/codeql-analysis.yml
Labels: Tests
